### ISSUE TITLE
Implement Isolation Criteria for Consuelo and Dark Sky

### ISSUE THREAD

**Issue by marxwillia** [drphilmarshall/LocalGroupHaloProps#41] opened 2015-01-22 22:45 UTC
Dark Sky is finally done, and we should definitely use it for this project.  It has 64 times the volume at twice the resolution.  This means that the isolation criteria needs to be implemented instead of just using the premade files that Michael organized.

**Comment by drphilmarshall** [comment] 2015-01-22 22:52
Good point. Can you reconstruct Michael's procedure? If push comes to shove
we can dial him in, but let's try and do it ourselves if we can. Yao had
opinions on the particular choices, you recall - and certainly we want to
be robust to them (which means experimenting with a few different options!)

**Comment by yymao** [comment] 2015-04-07 18:33
Just to follow up on this --- from my experience the isolation criteria would have significant impact on the prior (and hence on the posterior). It would be good check how much the result would change when some of the isolation criteria are lessen.

**Comment by drphilmarshall** [comment] 2015-04-08 00:19
Agreed - it's an important (and previously neglected) systematic check.

**Comment by marxwillia** [comment] 2015-04-22 23:02
I think we have a rather significant problem:  Take a look at the following notebook, specifically at the cyan corner plot.  

http://nbviewer.ipython.org/github/drphilmarshall/LocalGroupHaloProps/blob/master/triplets.ipynb

This is the Consuelo prior, and you will immediately notice that the 1D histograms are located in the wrong places.  For example, MW_D = 0.57 instead of 0.77.  This happened because I recently changed positions to be physical instead of comoving.  I am afraid that Michael implemented his isolation criteria using D=.77 comoving instead of physical, in which case we are using the wrong sample of halos.

**Comment by marxwillia** [comment] 2015-04-22 23:57
Michael's bgc2 files are already in physical units, so there is actually no problem as long as the h-factor is not double counted.

**Comment by marxwillia** [comment] 2015-04-23 07:56
Following discussion with @rhw  and @yymao a new document has been added describing the new implementation criteria.  Please read and discuss!

https://github.com/drphilmarshall/LocalGroupHaloProps/blob/master/doc/notes/isolation-criteria.txt

**Comment by drphilmarshall** [comment] 2015-04-24 12:34
Good! Thanks for posting. 

* I guess tripletsCase1 is interesting because it has the same M31 > MW criterion in it. How strongly do we believe in this, though? I would have thought that we'd always want to relax this, like in tripletsCase2. Now I'm wondering if we ought to make pairsCase1, and draw symmetric inferences about the MW and M31 halo mass (which I think can't be separated with just M31 kinematic data).

* I see three control parameters in this file: Riso = 2Mpc, DM31cut = 970kpc, DM33cut = 400kpc. Shrinking the D's will make everything go faster, but we should check the effect of that on the inferred masses. I guess a large DM33cut is interesting to separate the effect of the existence of M33 from the kinematics of M33. Is it Riso that we are most worried about when considering systematics due to isolation criteria, or something else?

**Comment by marxwillia** [comment] 2015-04-24 12:41
The posterior PDF's should not be that sensitive to small perturbations in DM31 and DM33 cuts because the likelihood function only significantly weights LG analogs centered sharply at the true values.  As for making a pairsCase1, I'm not sure that is really necessary because it would not actually pick out any new pairs.  That is simply a labeling decision: do we call the small member of the pair MW or M31?  Risa says that there is strong evidence that MW is smaller.

**Comment by drphilmarshall** [comment] 2015-04-24 14:17
I'm not sure about this. In VdM++2012, they use an M31 virial mass of about
1.4+/-0.4 x10^12 Msun, while the MW virial mass is only known to +/-0.3,
isn't it? I would think the question of which halo was heavier was still on
the table... @rhw?

I guess including all the pairs twice, but relabelled, would make the PDFs
for each halo mass double-peaked, and so would illustrate how the M31
kinematic data don't constrain the individual halo masses (without changing
the constraint on the sum of the masses). We would then see that the
association of M33  with M31 would push the mass of M31 higher and the MW
lower, I expect, and the kinematics of M33 to constrain things still
further.

**Comment by yymao** [comment] 2015-04-24 17:30
See [this](https://slack-files.com/T02FZEFV0-F04GLTZF6-0c8f5c6d33) for my revision.

Including all pairs twice would just make the posteriors of masses of MW and of M31 identical in the case that only pairs are considered. 

For triplets, if we define M31 to be the one whose brightest satellite is brighter than the brightest satellite of the other, then there's no "including pairs twice" thing because for each pair M31 is already defined.

**Comment by rhw** [comment] 2015-04-28 10:24
I agree that Yao's definition works -- it does not require pre-assuming which galaxy is more massive, just that one of them is.  One can then just decide (or not) to do this at the end, when you assign the labels MW and M31.

**Comment by drphilmarshall** [comment] 2015-04-28 10:29
OK. I definitely agree that labelling M31 by its ownership of M33 make
sense. If we wanted to preserve the symmetry between M31 and MW in the
pairs analysis, I guess we could do the assignment at random. @marxwillia,
what did Gonzales et al do? Part of our brief is to check their results.

**Comment by marxwillia** [comment] 2015-05-06 07:17
I am meeting with @yymao  on Wednesday to discuss dark sky.

**Comment by drphilmarshall** [comment] 2015-05-06 10:45
OK, sounds good! If this is not going to make it into the thesis, you should reassign this issue to the paper milestone.

**Comment by drphilmarshall** [comment] 2015-05-08 15:29
Update: to solve the h problem (#59) @marxwillia is going to remake the Consuelo catalogs so that we know what units we are working in. And then we can also test our robustness to isolation criteria etc. And compare with Dark Sky. So, this is senior thesis critical!

**Comment by drphilmarshall** [comment] 2015-05-08 15:38
New isolation criterion: M31's second biggest subhalo is less massive than 80 km/s, so only accept triplets of exactly three halos.

**Comment by marxwillia** [comment] 2015-05-10 00:06
Two quick questions for @mbusha 

1.  You provided us files from all 50 Consuelo boxes, but we only have the hlists from about 20 at SLAC.  The hlists we have are found at: /nfs/slac/g/ki/ki20/cosmo/behroozi/Consuelo

Do you know where the entire set of hlists can be found?

2.  In the files you provided us with the isolation criteria already applied, did you convert the masses to physical units (ie did you multiply by h=0.7)? I am referring specifically to the files ending in "bgc2.txt" found at: /nfs/slac/g/ki/ki04/mbusha/projects/LasDamas/Simulations/Consuelo/LG_project.

**Comment by drphilmarshall** [comment] 2015-05-11 14:03
A reply from Michael:

"The question about the location of the hlists files is probably best directed at Peter Behroozi, but I think that 20 is actually all that exists.  The issue is that all the snapshots weren't saved long enough to create merger trees, so those 20 might be all that we have in that regards.  

As for the second questions, the bgc2.txt files should all be in h=1.0 units -- I definitely don't see any code anywhere that has me converting things. "

**Comment by drphilmarshall** [comment] 2015-05-11 14:04
I think this means you are all set to complete the first look Consuelo analysis, @marxwillia !

**Closed** 2015-05-13 05:16 UTC
Labels: Halo Sampling
